
services:
  db:
    image: mysql:8.0
    container_name: donnicola_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: donicola_password
      MYSQL_DATABASE: donicola       
      MYSQL_USER: user               
      MYSQL_PASSWORD: password          
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entry-point-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"] # Usa las credenciales que configuraste
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: donnicola_backend
    ports:
      - "8080:8080" 
    environment:

      DB_HOST: db
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_DATABASE: ${DB_DATABASE:-donicola}
      DB_PORT: ${DB_PORT:-3306}
      PORT: 8080
      FRONTEND_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: donnicola_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  db_data: