version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: stock_sales_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: donicola_password
      MYSQL_DATABASE: donicola       
      MYSQL_USER: user               
      MYSQL_PASSWORD: password          
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entry-point-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: stock_sales_backend
    ports:
      - "8080:8080" 
    environment:

      DB_HOST: db
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_DATABASE: ${DB_DATABASE:-mydatabase}
      DB_PORT: ${DB_PORT:-3306}
      PORT: 8080
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_sales_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  db_data: